name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.190.0
        with:
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Rubocop
        run: |
          bundle exec rubocop

      - name: Build and test with rspec
        run: |
          bundle exec rspec
